version: '3.8'
services:

  postgres:
    image: postgres:13.4-alpine
    shm_size: '256m'
    environment:
      POSTGRES_USER: darkroom
      POSTGRES_PASSWORD: darkroom-password
      POSTGRES_DB: darkroom
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    # If you need to access the DB locally. Could be a security risk to expose DB.
    ports:
      - "5432:5432"
    command:
      -c checkpoint_completion_target=0.9
      -c work_mem=96MB
      -c wal_writer_delay=20ms
      -c synchronous_commit=off
      -c wal_buffers=32MB
      -c min_wal_size=2GB
      -c max_wal_size=4GB
      -c effective_io_concurrency=200
      -c random_page_cost=1.1
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 120s
      retries: 10
    restart: always

  minio:
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data/images:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-password
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.23-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      retries: 5
    restart: always
